/* Generated by Cython 0.25.1 */

#ifndef __PYX_HAVE__dependency_injector__providers__utils
#define __PYX_HAVE__dependency_injector__providers__utils


#ifndef __PYX_HAVE_API__dependency_injector__providers__utils

#ifndef __PYX_EXTERN_C
  #ifdef __cplusplus
    #define __PYX_EXTERN_C extern "C"
  #else
    #define __PYX_EXTERN_C extern
  #endif
#endif

#ifndef DL_IMPORT
  #define DL_IMPORT(_T) _T
#endif

__PYX_EXTERN_C DL_IMPORT(PyObject) *__pyx_v_19dependency_injector_9providers_5utils_CLASS_TYPES;

#endif /* !__PYX_HAVE_API__dependency_injector__providers__utils */

#if PY_MAJOR_VERSION < 3
PyMODINIT_FUNC initutils(void);
#else
PyMODINIT_FUNC PyInit_utils(void);
#endif

#endif /* !__PYX_HAVE__dependency_injector__providers__utils */
